name: htsuyoshiy.online

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Create build dir
        run: mkdir build
      - name: Build website
        uses: helaili/jekyll-action@2.5.0
        with:
          build_only: true
          build_dir: build
      - name: Upload to S3
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --exclude="*.md" --exclude="Dockerfile" --exclude="Makefile" --exclude=".git"
